### PR TITLE
CD-154649 Use knapsack to reoder items in avalanche

### PR DESCRIPTION
**Pull request by revathi-murali**
## JIRA

[Main JIRA Ticket](https://coupadev.atlassian.net/browse/CD-154649)

## Code Reviewers

- [ ] @johnwu96822 

## Summary of Issue

Use knapsack to reoder items in avalanche

## Summary of Change

Added new class `WorkerReport` that will be used by the avalanche workers to generate the report

### CODE REVIEW

**Comment by johnwu96822** [comment]
@revathi-murali Why do we need this change? Can't existing knapsack feature generate the report on each worker (which would contain report for only one file on each work)?

**Comment by revathi-murali** [comment]
@johnwu96822 Existing knapsack code, takes the report_path from the env variable. Since each worker is gonna generate the report, the file keeps overriding.

**Comment by johnwu96822** [comment]
I see. Though typically what you'd do in this case is to set a different env variable for each worker (like with the process ID in the path) so that they don't write to the same file. I'd prefer that over a code change. But it's up to you.

**Comment by revathi-murali** [comment]
Instead of setting different env variable to each worker, I would prefer this.

**Comment by revathi-murali** [comment]
@johnwu96822 I rechecked the knapsack code and looks like though it takes the path from the env variable, there is an option to configure the path by calling `Knapsack.report.config(report_path: <path>)`. So I can call config method to set the report_path. Hence this change is not required. Closing the PR

**Pull request closed without merging**
